/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { EnvironmentListRelationFilter } from "../../environment/base/EnvironmentListRelationFilter";
import { FlagDefinitionListRelationFilter } from "../../flagDefinition/base/FlagDefinitionListRelationFilter";
import { StringFilter } from "../../util/StringFilter";
@InputType()
class ProjectWhereInput {
  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  description?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => EnvironmentListRelationFilter,
  })
  @ValidateNested()
  @Type(() => EnvironmentListRelationFilter)
  @IsOptional()
  @Field(() => EnvironmentListRelationFilter, {
    nullable: true,
  })
  environments?: EnvironmentListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => FlagDefinitionListRelationFilter,
  })
  @ValidateNested()
  @Type(() => FlagDefinitionListRelationFilter)
  @IsOptional()
  @Field(() => FlagDefinitionListRelationFilter, {
    nullable: true,
  })
  flags?: FlagDefinitionListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  name?: StringFilter;
}
export { ProjectWhereInput };
