/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AccountWhereUniqueInput } from "../../account/base/AccountWhereUniqueInput";
import { ValidateNested, IsString, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { EnvironmentCreateNestedManyWithoutProjectsInput } from "./EnvironmentCreateNestedManyWithoutProjectsInput";
import { FlagDefinitionCreateNestedManyWithoutProjectsInput } from "./FlagDefinitionCreateNestedManyWithoutProjectsInput";
@InputType()
class ProjectCreateInput {
  @ApiProperty({
    required: true,
    type: () => AccountWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AccountWhereUniqueInput)
  @Field(() => AccountWhereUniqueInput)
  account!: AccountWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: () => EnvironmentCreateNestedManyWithoutProjectsInput,
  })
  @ValidateNested()
  @Type(() => EnvironmentCreateNestedManyWithoutProjectsInput)
  @IsOptional()
  @Field(() => EnvironmentCreateNestedManyWithoutProjectsInput, {
    nullable: true,
  })
  environments?: EnvironmentCreateNestedManyWithoutProjectsInput;

  @ApiProperty({
    required: false,
    type: () => FlagDefinitionCreateNestedManyWithoutProjectsInput,
  })
  @ValidateNested()
  @Type(() => FlagDefinitionCreateNestedManyWithoutProjectsInput)
  @IsOptional()
  @Field(() => FlagDefinitionCreateNestedManyWithoutProjectsInput, {
    nullable: true,
  })
  flag?: FlagDefinitionCreateNestedManyWithoutProjectsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;
}
export { ProjectCreateInput };
